apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend-app
  template:
    metadata:
      labels:
        app: react-frontend-app
    spec:
      containers:
        - name: react-frontend-container
          image: 676206914267.dkr.ecr.us-east-1.amazonaws.com/techcloud-academy-frontend-apps:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  type: NodePort
  selector:
    app: react-frontend-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32411  # Custom nodePort (default range 30000-32767)
